//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLOA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLOAContainer : DbContext
    {
        public DLOAContainer()
            : base("name=DLOAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfoSet { get; set; }
        public virtual DbSet<RoleInfo> RoleInfoSet { get; set; }
        public virtual DbSet<ActionInfo> ActionInfoSet { get; set; }
        public virtual DbSet<UserAction> UserActionSet { get; set; }
        public virtual DbSet<WorkFlowModel> WorkFlowModelSet { get; set; }
        public virtual DbSet<WorkFlowInstance> WorkFlowInstanceSet { get; set; }
        public virtual DbSet<WorkFlowStep> WorkFlowStepSet { get; set; }
    }
}
