//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowStep
    {
        public int StepId { get; set; }
        public int NextId { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
        public int InstanceId { get; set; }
        public bool IsOver { get; set; }
        public bool Comment { get; set; }
    
        public virtual WorkFlowInstance WorkFlowInstance { get; set; }
    }
}
