//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkFlowInstance()
        {
            this.WorkFlowStep = new HashSet<WorkFlowStep>();
        }
    
        public int InstanceId { get; set; }
        public string InstantTitle { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
        public string InstanceGuid { get; set; }
        public int InstanceState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlowStep> WorkFlowStep { get; set; }
    }
}
